### ISSUE TITLE
Feature request: See if someone will be there

### ISSUE THREAD

**Issue by tklae** [geidies/puresence#1]
**As** someone who thinks about going to Werkstatt early in the morning
**I want** to know if someone else will be at Werkstatt once I arrive
**So that** I can start travelling before someone has already arrived at Werkstatt.

**Comment by geidies** [comment]
### Modelling

Add a third state besides true and false. In this case, contrary to [common implementations](http://thedailywtf.com/articles/What_Is_Truth_0x3f_) of the three-valued boolean, it is called `plan`.
`plan` can only be set from a status of false, it will not override if someone is already there.
The `plan` status will expire after a user-defined time, after which it will fall back to false - the user still needs to log in when arriving.
Plan will use a second key, `eta`, which will have the timestamp of someone setting the `plan` status, +X seconds which can be user-configured with the request. It can only be overridden by a user that would arrive earlier.

### UI

Prevalent color should be yellowish orange or orange-ish yellow. 

#### set

Add a third button. It might be necessary to rearrange the buttons from side-by-side to another layout. When the User clicks/touches the button, he/she will be presented with options - 15/30/45/60 minutes ETA.

#### get

Add a third picture, plus information about the ETA.
